# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08cc80743e22eca7b2e90b115263cd012bacbb118de76391e7f33c97daccb9209a21413bcb9a2dad8cbc699728723ec69f213cf45b13b69119bdf1f7388dd894

test:
  secret_key_base: c38bcbaba436ba953a88277032e9ff6389c68cc062a2545fa4b362d10abd206404a101286c712c9453d552dfc6cc01b6ddeee0e15085f510bb9f7c4581e73b9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
